version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: '0'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
     - '3000:3000'
    volumes:
      - '$PWD/data:/var/lib/grafana'
    networks:
      - shared_network

networks:
  shared_network:
    external:
      name: shared_network
